In [2]:
import numpy as np

a = np.array([[0,1,1], [1,0,0], [0,1,1]])
kernel = np.array([[1,0,1], [0,1,0], [1,0,1]])

print(a * kernel)

[[0 0 1]
 [0 0 0]
 [0 0 1]]


In [4]:
b = np.array([[1,1,0], [0,0,1], [1,1,0]])
print(b * kernel)

SyntaxError: unexpected EOF while parsing (3187457233.py, line 2)

In [7]:
img = np.array([
  [0,1,1,0,0,0],
  [1,0,0,1,0,0],
  [0,1,1,0,0,0],
  [1,0,0,1,0,0],
  [0,1,1,0,0,0],
  [0,0,0,0,0,0]
])
print(img)

[[0 1 1 0 0 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]]
